version: '2.1'

orbs:
  terraform: circleci/terraform@1.2.1

workflows:
  deploy_infra:
    jobs:
      - terraform/validate:
          checkout: true
          context: terraform

      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          run:
            name: Plan
            command: terraform plan -chdir=/.circleci/config.yml

      - terraform/apply:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: master
          requires:
            - terraform/plan
